TRUNCATE TABLE main_UNIVERSAL.TRANSACCION_ENRIQUECIDA;

-- TRANSACCION_PERSONA_ENRIQUECIDA_1

DROP TABLE IF EXISTS main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_1;
CREATE TEMPORARY TABLE main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_1(
ID_PERSONA STRING,
NOMBRE_PERSONA STRING,
EDAD_PERSONA INT,
SALARIO_PERSONA DOUBLE,
ID_EMPRESA_PERSONA STRING,
MONTO_TRANSACCION DOUBLE,
FECHA_TRANSACCION STRING,
ID_EMPRESA_TRANSACCION STRING
)
STORED AS PARQUET;

INSERT INTO main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_1
SELECT
T.ID_PERSONA AS ID_PERSONA,
P.NOMBRE AS NOMBRE_PERSONA,
P.EDAD AS EDAD_PERSONA,
P.SALARIO AS SALARIO_PERSONA,
P.ID_EMPRESA AS ID_EMPRESA_PERSONA,
T.MONTO AS MONTO_TRANSACCION,
T.FECHA AS FECHA_TRANSACCION,
T.ID_EMPRESA AS ID_EMPRESA_TRANSACCION
FROM
main_UNIVERSAL.TRANSACCION T
JOIN main_UNIVERSAL.PERSONA P
ON T.ID_PERSONA = P.ID;

SELECT * FROM main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_1 LIMIT 10;

-- TRANSACCION_PERSONA_ENRIQUECIDA_2

DROP TABLE IF EXISTS main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_2;
CREATE TEMPORARY TABLE main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_2(
ID_PERSONA STRING,
NOMBRE_PERSONA STRING,
EDAD_PERSONA INT,
SALARIO_PERSONA DOUBLE,
TRABAJO_PERSONA STRING,
MONTO_TRANSACCION DOUBLE,
FECHA_TRANSACCION STRING,
ID_EMPRESA_TRANSACCION STRING
)
STORED AS PARQUET;

INSERT INTO main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_2
SELECT
T.ID_PERSONA AS ID_PERSONA,
T.NOMBRE_PERSONA AS NOMBRE_PERSONA,
T.EDAD_PERSONA AS EDAD_PERSONA,
T.SALARIO_PERSONA AS SALARIO_PERSONA,
E.NOMBRE AS TRABAJO_PERSONA,
T.MONTO_TRANSACCION AS MONTO_TRANSACCION,
T.FECHA_TRANSACCION AS FECHA_TRANSACCION,
T.ID_EMPRESA_TRANSACCION AS ID_EMPRESA_TRANSACCION
FROM
main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_1 T
JOIN main_UNIVERSAL.EMPRESA E
ON T.ID_EMPRESA_PERSONA = E.ID;

SELECT * FROM main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_2 LIMIT 10;

-- TRANSACCION_PERSONA_EMPRESA_ENRIQUECIDA

DROP TABLE IF EXISTS main_UNIVERSAL.TRANSACCION_PERSONA_EMPRESA_ENRIQUECIDA;
CREATE TEMPORARY TABLE main_UNIVERSAL.TRANSACCION_PERSONA_EMPRESA_ENRIQUECIDA(
ID_PERSONA STRING,
NOMBRE_PERSONA STRING,
EDAD_PERSONA INT,
SALARIO_PERSONA DOUBLE,
TRABAJO_PERSONA STRING,
MONTO_TRANSACCION DOUBLE,
FECHA_TRANSACCION STRING,
EMPRESA_TRANSACCION STRING
)
STORED AS PARQUET;

INSERT INTO main_UNIVERSAL.TRANSACCION_PERSONA_EMPRESA_ENRIQUECIDA
SELECT
T.ID_PERSONA AS ID_PERSONA,
T.NOMBRE_PERSONA AS NOMBRE_PERSONA,
T.EDAD_PERSONA AS EDAD_PERSONA,
T.SALARIO_PERSONA AS SALARIO_PERSONA,
T.TRABAJO_PERSONA AS TRABAJO_PERSONA,
T.MONTO_TRANSACCION AS MONTO_TRANSACCION,
T.FECHA_TRANSACCION AS FECHA_TRANSACCION,
E.NOMBRE AS EMPRESA_TRANSACCION
FROM
main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_2 T
JOIN main_UNIVERSAL.EMPRESA E
ON T.ID_EMPRESA_TRANSACCION = E.ID;

SELECT * FROM main_UNIVERSAL.TRANSACCION_PERSONA_EMPRESA_ENRIQUECIDA LIMIT 10;

-- Inserción final

SET hive.exec.dynamic.partition=true;
SET hive.exec.dynamic.partition.mode=nonstrict;
SET hive.exec.max.dynamic.partitions=9999;
SET hive.exec.max.dynamic.partitions.pernode=9999;

INSERT OVERWRITE TABLE main_UNIVERSAL.TRANSACCION_ENRIQUECIDA
PARTITION (FECHA_TRANSACCION)
SELECT
ID_PERSONA,
NOMBRE_PERSONA,
EDAD_PERSONA,
SALARIO_PERSONA,
TRABAJO_PERSONA,
MONTO_TRANSACCION,
EMPRESA_TRANSACCION,
FECHA_TRANSACCION
FROM
main_UNIVERSAL.TRANSACCION_PERSONA_EMPRESA_ENRIQUECIDA;

SELECT * FROM main_UNIVERSAL.TRANSACCION_ENRIQUECIDA LIMIT 10;

-- Eliminación de tablas temporales

DROP TABLE IF EXISTS main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_1;
DROP TABLE IF EXISTS main_UNIVERSAL.TRANSACCION_PERSONA_ENRIQUECIDA_2;
DROP TABLE IF EXISTS main_UNIVERSAL.TRANSACCION_PERSONA_EMPRESA_ENRIQUECIDA;