-- beeline -u jdbc:hive2://

-- Creación de esquema
CREATE SCHEMA IF NOT EXISTS MAIN_SMART_PROYECTO_4;

-- Creación de tabla
CREATE EXTERNAL TABLE MAIN_SMART_PROYECTO_4.PERSONA(
KEY STRING,
NOMBRE STRING ,
TELEFONO STRING,
CORREO STRING ,
FECHA_INGRESO STRING,
EDAD STRING,
SALARIO STRING,
ID_EMPRESA STRING
)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES ("hbase.columns.mapping" = "
DATOS:NOMBRE,
DATOS:TELEFONO,
DATOS:CORREO,
DATOS:FECHA_INGRESO,
DATOS:EDAD,
DATOS:SALARIO,
DATOS:ID_EMPRESA
")
TBLPROPERTIES ("hbase.table.name" = "MAIN_SMART_PROYECTO_4:PERSONA");

-- Creación de tabla
CREATE EXTERNAL TABLE MAIN_SMART_PROYECTO_4.EMPRESA(
KEY STRING,
NOMBRE STRING
)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES ("hbase.columns.mapping" = "
DATOS:NOMBRE
")
TBLPROPERTIES ("hbase.table.name" = "MAIN_SMART_PROYECTO_4:EMPRESA");

-- Creación de tabla
CREATE EXTERNAL TABLE MAIN_SMART_PROYECTO_4.TRANSACCION_ENRIQUECIDA(
KEY STRING,
ID_PERSONA STRING,
NOMBRE_PERSONA STRING,
ID_EMPRESA STRING,
NOMBRE_EMPRESA STRING,
FECHA STRING,
HORA STRING,
MONTO STRING
)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES ("hbase.columns.mapping" = "
PERSONA:ID,
PERSONA:NOMBRE,
EMPRESA:ID,
EMPRESA:NOMBRE,
TRANSACCION:FECHA,
TRANSACCION:HORA,
TRANSACCION:MONTO
")
TBLPROPERTIES ("hbase.table.name" = "MAIN_SMART_PROYECTO_4:TRANSACCION_ENRIQUECIDA");