-- beeline -u jdbc:hive2://

-- Inserción de datos sobre la tabla HBASE "MAIN_SMART_PROYECTO_4:PERSONA"
INSERT INTO MAIN_SMART_PROYECTO_4.PERSONA 
SELECT
ID,
NOMBRE,
TELEFONO,
CORREO,
FECHA_INGRESO,
EDAD,
SALARIO,
ID_EMPRESA
FROM
main_UNIVERSAL.PERSONA;

-- Inserción de datos sobre la tabla HBASE "MAIN_SMART_PROYECTO_4:EMPRESA"
INSERT INTO MAIN_SMART_PROYECTO_4.EMPRESA 
SELECT
ID,
NOMBRE
FROM
main_UNIVERSAL.EMPRESA;

-- Verificamos que los datos se han insertado
SELECT * FROM MAIN_SMART_PROYECTO_4.PERSONA LIMIT 10;
SELECT * FROM MAIN_SMART_PROYECTO_4.EMPRESA LIMIT 10;
SELECT * FROM MAIN_SMART_PROYECTO_4.TRANSACCION_ENRIQUECIDA LIMIT 10;