#Valor del parámetro
username = "MIUSUARIO"

#Reporte 5

dfReporte5 = spark.sql("""
SELECT 
T.NOMBRE_PERSONA NOMBRE_PERSONA,
SUM(T.MONTO_TRANSACCION) SUMA_TRANSACCIONES,
MAX(T.MONTO_TRANSACCION) MAYOR_TRANSACCION,
MIN(T.MONTO_TRANSACCION) MENOR_TRANSACCION,
AVG(T.MONTO_TRANSACCION) PROMEDIO_TRANSACCIONES
FROM 
{var:username}_UNIVERSAL.TRANSACCION_ENRIQUECIDA T
GROUP BY
T.NOMBRE_PERSONA
""".\
replace("{var:username}", username)
)

dfReporte5.show()